[font]
size = 12.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "B", mods = "Alt", chars = "\u001bb" },
  { key = "F", mods = "Alt", chars = "\u001bf" },
  { key = "D", mods = "Alt", chars = "\u001bd" },
  { key = "W", mods = "Alt", chars = "\u001bw" },
  { key = "X", mods = "Alt", chars = "\u001bx" }
]
